SECRET_KEY = 'SecretKey'
API_KEY = 'ApiKey'

APP_ENV_TESTING = 'testing'
APP_ENV_DEVELOPMENT = 'development'
APP_ENV_STAGING = 'staging'
APP_ENV_PRODUCTION = 'production'
APP_ENV = ''

SQLALCHEMY_TRACK_MODIFICATIONS = False
